# Generated by Django 5.0.1 on 2025-02-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fd_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.fd_menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.fd_user')),
            ],
        ),
    ]
