# Generated by Django 5.1.6 on 2025-02-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Foodapp', '0001_initial'),
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_canteen'),
        ),
        migrations.AddField(
            model_name='fd_menu',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.fd_category'),
        ),
        migrations.AddField(
            model_name='fd_menu',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_canteen'),
        ),
        migrations.AddField(
            model_name='fd_cart',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.fd_menu'),
        ),
        migrations.AddField(
            model_name='fd_cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.fd_user'),
        ),
    ]
