# Generated by Django 5.1 on 2025-05-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0002_fd_cart'),
        ('Foodapp', '0002_initial'),
    ]

    operations = [
    ]
