# Generated by Django 5.1 on 2025-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0003_merge_0002_fd_cart_0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fd_user',
            old_name='email',
            new_name='fd_email',
        ),
        migrations.RenameField(
            model_name='fd_user',
            old_name='password',
            new_name='fd_password',
        ),
        migrations.RenameField(
            model_name='fd_user',
            old_name='phone',
            new_name='fd_phone',
        ),
        migrations.RenameField(
            model_name='fd_user',
            old_name='role',
            new_name='fd_role',
        ),
        migrations.RenameField(
            model_name='fd_user',
            old_name='username',
            new_name='fd_username',
        ),
    ]
