# Generated by Django 5.1 on 2025-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationMaster', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_offer',
        ),
    ]
