# Generated by Django 5.1 on 2025-05-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('WebAdmin', '0002_tbl_canteen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='end_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_concessions', to='WebAdmin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='start_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_concessions', to='WebAdmin.tbl_place'),
        ),
    ]
